services:
  musicmetrics:
    image: node:alpine
    container_name: musicmetrics
    entrypoint: /bin/sh -c "npm install && npm run dev"
    ports:
      - "0.0.0.0:8080:8080"
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
